Youtube: [Movie Recommendation System with Collaborative Filtering](https://youtu.be/3ecNC-So0r4)

### Random values

In [1]:
import numpy as np
import pandas as pd

np.random.seed(0)

In [2]:
n=100
df2 = pd.DataFrame(np.random.randint(0, 6, (1000, n)), columns=[f'Movie{i+1}' for i in range(n)])
df2

,Movie1,Movie2,Movie3,Movie4,Movie5,Movie6,Movie7,Movie8,Movie9,Movie10,...,Movie91,Movie92,Movie93,Movie94,Movie95,Movie96,Movie97,Movie98,Movie99,Movie100
0,4,5,0,3,3,3,1,3,5,2,...,5,5,0,1,5,1,3,0,5,0
1,1,2,4,2,0,5,3,2,2,5,...,5,3,1,0,0,4,3,3,1,5
2,5,0,0,1,2,0,3,5,1,1,...,5,1,1,2,1,5,4,5,2,5
3,5,4,4,5,5,2,3,5,3,1,...,4,4,2,5,1,2,5,0,3,0
4,2,4,3,2,1,2,1,4,5,1,...,4,3,5,3,2,1,0,4,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4,0,1,2,3,2,5,1,3,0,...,5,4,2,4,4,3,3,1,1,3
996,5,4,5,5,4,5,4,0,1,2,...,5,0,1,1,1,1,4,0,5,3
997,2,5,3,1,2,0,4,5,4,1,...,1,3,2,1,4,3,0,4,0,4
998,1,4,5,2,3,3,3,4,4,5,...,1,3,2,5,2,1,5,3,5,1
999,2,4,4,5,2,0,3,3,2,5,...,3,2,1,1,1,5,5,3,0,0

In [3]:
df2_corr = df2.corr()
df2_corr

,Movie1,Movie2,Movie3,Movie4,Movie5,Movie6,Movie7,Movie8,Movie9,Movie10,...,Movie91,Movie92,Movie93,Movie94,Movie95,Movie96,Movie97,Movie98,Movie99,Movie100
Movie1,1.000000,0.004256,-0.012360,-0.007945,-0.005208,-0.011779,-0.020658,-0.008370,-0.019390,0.009365,...,-0.015087,0.006971,0.000004,-0.001189,0.007712,-0.000580,-0.001011,-0.080407,0.007166,0.002297
Movie2,0.004256,1.000000,0.065024,0.067908,0.018726,-0.096036,-0.039841,0.013355,0.004177,-0.009665,...,0.020345,0.028043,-0.024126,-0.040503,0.030086,0.002427,0.009607,0.023468,0.011496,0.011796
Movie3,-0.012360,0.065024,1.000000,-0.034011,-0.013543,-0.020429,-0.030835,-0.002802,0.010300,0.086714,...,-0.044012,-0.006408,0.001551,-0.007725,0.014363,-0.002126,0.008158,0.013097,-0.007306,-0.006688
Movie4,-0.007945,0.067908,-0.034011,1.000000,-0.043943,-0.005847,0.014176,0.005727,0.009996,-0.022473,...,0.018168,0.065449,-0.010601,-0.012989,0.021402,-0.006877,-0.000546,0.018051,0.068946,0.022577
Movie5,-0.005208,0.018726,-0.013543,-0.043943,1.000000,0.015796,0.023486,0.049848,-0.061514,-0.001762,...,-0.012528,0.011234,-0.020529,0.014598,0.020873,0.029653,0.001285,-0.022979,0.025807,-0.011947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Movie96,-0.000580,0.002427,-0.002126,-0.006877,0.029653,-0.015649,0.020059,0.040298,0.033908,-0.017391,...,0.017812,-0.052651,-0.000171,0.040029,-0.054018,1.000000,-0.029171,-0.041963,-0.014088,0.021214
Movie97,-0.001011,0.009607,0.008158,-0.000546,0.001285,-0.027333,0.010231,-0.039368,-0.001987,0.072719,...,-0.059165,0.003829,0.030828,0.029522,0.031737,-0.029171,1.000000,-0.019076,0.002104,0.053447
Movie98,-0.080407,0.023468,0.013097,0.018051,-0.022979,0.018158,-0.014361,0.049414,-0.014615,0.024886,...,-0.040207,-0.000866,-0.021946,0.013142,-0.020999,-0.041963,-0.019076,1.000000,-0.021336,0.040241
Movie99,0.007166,0.011496,-0.007306,0.068946,0.025807,0.003686,0.018552,0.014242,0.036177,-0.020017,...,0.047453,0.005684,-0.012531,0.005657,0.010793,-0.014088,0.002104,-0.021336,1.000000,0.034278
Movie100,0.002297,0.011796,-0.006688,0.022577,-0.011947,-0.015422,0.035492,0.003773,-0.057240,0.025262,...,0.047644,0.025947,-0.020802,-0.038103,-0.012872,0.021214,0.053447,0.040241,0.034278,1.000000

In [4]:
def recommendation(movie, rating):
    sim = df2_corr[movie] * (rating - 2.5)
    # sim = sim.sort_values(ascending=False)
    return sim

recommendation('Movie10', 2).sort_values(ascending=False)

Movie34    0.034452
Movie68    0.033783
Movie92    0.029611
Movie67    0.028771
Movie35    0.028401
             ...
Movie76   -0.036218
Movie97   -0.036359
Movie3    -0.043357
Movie16   -0.052510
Movie10   -0.500000
Name: Movie10, Length: 100, dtype: float64

In [5]:
import random

In [6]:
a = [1,2,3,4]
random.shuffle(a)
a[:3]

[4, 1, 2]

In [7]:
movies = [f'Movie{i+1}' for i in range(n)]
sim = pd.DataFrame()
random.shuffle(movies)
ratings = [(movies[i], random.randint(0, 5)) for i in range(20)]

for movie, r in ratings:
    sim = pd.concat([sim, recommendation(movie, r)], axis=1)

sim.sum(axis=1).sort_values(ascending=False)

Movie33    2.402015
Movie78    2.379995
Movie27    2.018763
Movie7     1.680634
Movie81    1.656713
             ...
Movie73   -1.924940
Movie74   -2.299746
Movie15   -2.586350
Movie40   -2.607493
Movie60   -2.807242
Length: 100, dtype: float64